### ISSUE TITLE
comment 2

### ISSUE THREAD

**Issue by Keeper991** [hyejin4169/react_my_magazine#1]
과제 마무리하느라 고생많으셨습니다 👏

* 잘 구현해주셔서, 자잘한 comment와 발견한 버그를 남기도록 하겠습니다..👍
* 게시글 삭제의사를 물어보려면 `alert()` 대신 `confirm()`을 사용하는 것이 더 좋습니다.
* 게시글 이미지를 수정하고 새로운 게시글을 작성할 때, 이전에 수정한 이미지가 preview로 남아있는 버그가 있습니다.
게시글 작성하고 새로운 게시글을 작성할 땐 preview가 정상적으로 동작하는걸로 보아, 수정하는 부분을 집중적으로 확인해보시면 될 것 같습니다.

**Comment by hyejin4169** [comment]
안녕하세요, 코멘트 남겨주셔서 감사합니다! 말씀해주신 내용 확인 후 다음 과제에 보완하여 적용해보았습니다. :)
