### ISSUE TITLE
comment

### ISSUE THREAD

**Issue by dltmdrbtjd** [hyejin4169/react_my_magazine#2]
- PostList 컴포넌트 mounted시에 dispatch를 통해서 firebase에서 데이터를 가져와서 store에 넣어주는데 이걸 다시 PostList에서 store에서 가져와서 props로 Post컴포넌트에 주는것은 store도 쓰지만 props까지 사용하는 일입니다. PostList가 렌더링될때 Post컴포넌트도 렌더링되기 때문에 Post 컴포넌트에서 post_list를 가져와서 사용하고 PostList 컴포넌트에서는 props로 구지 내려주지않고 dispatch만 시켜주면 충분하겠죠? 이 부분에 대해서도 한 번 고민해보시면 좋을것 같습니다.😀 

- 추가로 Redux 및 상태관리 라이브러리에 대해서 왜 사용하는지와 어떤 장점을 얻게되는지를 찾아보시면 Redux또는 기타 상태관리 라이브러리를 사용하실때 더 이해도높게 사용하실수 있을거에요😎

- 그리고 store를 무조건 사용해야하는 이유는 없습니다. props만으로 사용해도 충분할 수 있고 구지 redux middleware를 이용해서 서버에서 데이터를 가져오지 않아도 괜찮은 경우도있죠. 이런 여러가지 경우를 생각해보시고 각각 상황에 맞게 구현하시면 좀 더 효율적으로 개발하실수 있을겁니다 !

**Comment by hyejin4169** [comment]
안녕하세요! 친절한 피드백 감사합니다. 리덕스에 대한 이해가 아직 부족하다고 생각했는데, 잘 짚어주셔서 좋네요! 공부 더 해보겠습니다. :)
